name: Deploy
on:
  push:
    branches:
      - firebaseDocumentation/master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@firebaseDocumentation/master
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@firebaseDocumentation/master
        with:
          args: deploy --only hosting:salt-and-sepr
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
